project:
  type: website

website:
  title: "Introduction to machine learning in Python with Scikit-learn"
  navbar:
    left:
      - href: index.qmd
        text: Home

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Slides"
        contents:
          - materials/slides/classification1.qmd
          - materials/slides/classification2.qmd
          - materials/slides/regression.qmd
          - materials/slides/ensembles.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  cache: true
  freeze: auto  # re-render only when source changes
